years: [2019, 2024]

cities:
  - Warsaw
  - Katowice

city_aliases:
  Warszawa: ["Warsaw", "Warszawa"]
  Katowice: ["Katowice"]

pm25:
  norm_limit: 15

pubmed:
  entrez_email: d.aniszewsk2@student.uw.edu.pl
  queries:
    - (PM2.5 OR "fine particulate matter")
  retmax: 100